services:
  - type: web
    name: telegram-messenger
    env: python
    plan: free
    buildCommand: ""
    startCommand: python server.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0